title:              SDIT Cordova Samarinda
email:              sditcordovasmr@gmail.com
description:        "Sekolah Dasar Islam Terpadu pertama di Samarinda."
keywords:           "sekolah islam, sdit, samarinda"
author:             Humas SDIT Cordova
baseurl:            "/"
phone:              6281234432180
message:            "Assalamu 'alaykum, SDIT Cordova."
enroll:
  call: "Daftar Sekarang via"
  contact: 085678876580
  btn: "Kontak WA Admin"
  url: "https://wa.me/6285678876580"

# Collections
collections:
  posts:
    title: Apa yang Tersedia di Blog Kami?
    output: true
    shorty: "Silakan baca artikel bermanfaat yang ditulis oleh para guru kami."
  pages:
    title: Laman
    output: true
    shorty: ""
  values:
    title: Nilai-Nilai Pegangan Kami
    output: true
    shorty: "Di SDIT Cordova, kami senantiasa mengutamakan kualitas pengajaran dan pengasuhan para siswa."
  features:
    title: Selamat Datang di SDIT Cordova
    output: true
    shorty: "Anak-anak adalah manusia kecil yang siap mengeksplorasi dunia."
  programs:
    title: Program-Program SDIT Cordova
    output: true
    shorty: "Kami telah mengembangkan berbagai program untuk beragam level usia dan keterampilan."
  extras:
    title: Ekstrakurikuler
    output: true
    shorty: "Selain kegiatan belajar-mengajar, kami juga menawarkan kegiatan ekstrakurikuler eksklusif untuk para siswa demi mengasah <em>soft skills</em> mereka."
  snapshots:
    title: Bagaimana Para Siswa Berkembang
    output: true
    shorty: "Mereka belajar, beristirahat sejenak, kemudian belajar dan bekerja lebih semangat lagi sambil berkolaborasi dengan satu sama lain."
  events:
    title: Bergabunglah di Acara Kami
    output: true
    shorty: "Kami secara berkala mengadakan beragam acara untuk membangun kedekatan di antara para siswa serta orang tua dan wali murid."
  civitas:
    title: Para Guru Kami Tercinta
    output: true
    shorty: "Hanya para guru yang terpelajar, mandiri, dan Islami yang bekerja bersama kami."
  parents:
    title: Apa Kata Orang Tua
    output: true
    shorty: "Anak-anak sholeh Anda adalah hadiah terbaik bagi kami."  
    
# Social Profiles
socials:
  - network: github
    url: https://github.com/ninjukustudio
  - network: instagram
    url: https://instagram.com/ninjukustudio
  - network: envelope
    url: mailto:sensei@ninjuku.studio
  - network: whatsapp
    url: https://wa.me/6285787706533
# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
